version: 2
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
