language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        ssh_known_hosts: xgitlab.cels.anl.gov
        apt:
          packages:
            - libblas-dev
            - liblapack-dev
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        ssh_known_hosts: xgitlab.cels.anl.gov
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - gcc-9
            - libblas-dev
            - liblapack-dev
    - os: osx
      osx_image: xcode11.4
      compiler: clang
      addons:
        ssh_known_hosts: xgitlab.cels.anl.gov

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:kimk/DSPThirdPartyLibs.git
  - cd DSPThirdPartyLibs
  - if [ $TRAVIS_OS_NAME == linux ]; then sh ./SCIPOptSuite-7.0.0-Linux.sh --skip-license; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sed -i 's|set(SCIPOPT_INC_DIR \"\"|set(SCIPOPT_INC_DIR \"${PWD}/include\"|g' ../UserConfig.cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sed -i 's|set(SCIPOPT_LIB_DIR \"\"|set(SCIPOPT_LIB_DIR \"${PWD}/lib\"|g' ../UserConfig.cmake; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sh ./SCIPOptSuite-7.0.0-Darwin.sh --skip-license; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sed -i'' -e 's|set(SCIPOPT_INC_DIR \"\"|set(SCIPOPT_INC_DIR \"${PWD}/include\"|g' ../UserConfig.cmake; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sed -i'' -e 's|set(SCIPOPT_LIB_DIR \"\"|set(SCIPOPT_LIB_DIR \"${PWD}/lib\"|g' ../UserConfig.cmake; fi
  - cat ../UserConfig.cmake
  - cd ..

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - echo "DONE"
  # - ctest --verbose