language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages: 
      - gfortran
      - libblas-dev
      - liblapack-dev
  homebrew:
    packages: 
      - gfortran
    update: true

# install: make get-deps

compiler:
  - clang
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - cmake . && make && make test
  