language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
            - libblas-dev
            - liblapack-dev
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - gcc-9
            - libblas-dev
            - liblapack-dev
    - os: osx
      osx_image: xcode11.4
      compiler: clang

addons:
  ssh_known_hosts: xgitlab.cels.anl.gov
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages: 
#       - gcc-9
#       - libblas-dev
#       - liblapack-dev
  # homebrew:
  #   packages: 
  #     - gfortran
  #   update: true

before_install:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:kimk/DSPThirdPartyLibs.git
  - ls DSPThirdPartyLibs
  - export PATH=/usr/lib:/usr/local/lib:${PATH}
  - export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:${LD_LIBRARY_PATH}
  - export DYLD_LIBRARY_PATH=/usr/lib:/usr/local/lib:${DYLD_LIBRARY_PATH}
  - gfortran -v

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - echo "DONE"
  # - ctest --verbose