language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages: 
      - gfortran-6
      - libblas-dev
      - liblapack-dev
  homebrew:
    packages: 
      - gfortran-6
    update: true

# install: make get-deps

compiler:
  - clang
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - FC=gfortran-6 cmake . && make && make test
  