language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.4

compiler:
  - clang
  - gcc

addons:
  apt:
    packages: 
      - gfortran
      - libblas-dev
      - liblapack-dev
  # homebrew:
  #   packages: 
  #     - gfortran
  #   update: true

before_install:
  - export PATH=/usr/lib:/usr/local/lib:${PATH}
  - export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:${LD_LIBRARY_PATH}
  - export DYLD_LIBRARY_PATH=/usr/lib:/usr/local/lib:${DYLD_LIBRARY_PATH}
  - gfortran -v

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

# script:
#   - make test