OPTION (READ_CONF "Read configuration file" OFF)
IF(READ_CONF)
  set(MA27_DIR "")
  set(MA57_DIR "")
  set(METIS_DIR "")
  set(OOQP_DIR "")
  set(SCIPOPTSUITE_DIR "")
  set(SMI_DIR "")
ENDIF(READ_CONF)
