OPTION (READ_CONF "Read configuration file" OFF)
IF(READ_CONF)
  set(MA27_DIR "/lcrc/project/NEXTGENOPT/DSP/extra/ma27-1.0.0")
  set(OOQP_DIR "/lcrc/project/NEXTGENOPT/DSP/extra/OOQP-0.99.25")
  set(SCIPOPTSUITE_DIR "/lcrc/project/NEXTGENOPT/DSP/extra/scipoptsuite-3.1.1")
  set(SMI_DIR "/lcrc/project/NEXTGENOPT/DSP/extra/Smi")
ENDIF(READ_CONF)
