OOQP: QpExampleData Class Reference
QpExampleData Class Reference
QpExample
#include <QpExampleData.h>
Public Member Functions
QpExampleData (LinearAlgebraPackage *la, int nx_in, int my_in, int mz_in)
virtual double datanorm ()
virtual void datainput ()
virtual void datarandom ()
virtual void print ()
void putQIntoAt (SymMatrix &M, int row, int col)
void putAIntoAt (SymMatrix &M, int row, int col)
void putCIntoAt (SymMatrix &M, int row, int col)
void Qmult (double beta, OoqpVector &y, double alpha, OoqpVector &x)
void Amult (double beta, OoqpVector &y, double alpha, OoqpVector &x)
void Cmult (double beta, OoqpVector &y, double alpha, OoqpVector &x)
void ATransmult (double beta, OoqpVector &y, double alpha, OoqpVector &x)
void CTransmult (double beta, OoqpVector &y, double alpha, OoqpVector &x)
void getg (OoqpVector &c_out)
void getb (OoqpVector &b_out)
void getd (OoqpVector &d_out)
GenMatrix * getC ()
Protected Attributes
LinearAlgebraPackage * la
int nx
int my
int mz
SymMatrix * Q
GenMatrix * A
GenMatrix * C
OoqpVector * c
OoqpVector * b
OoqpVector * d
Detailed Description
Data for the example QP formulation.
Member Function Documentation
void QpExampleData::Amult (double beta, OoqpVector & y, double alpha, OoqpVector & x) inline
y <- beta * y + alpha * A * x
References A, and DoubleMatrix::mult().
void QpExampleData::ATransmult (double beta, OoqpVector & y, double alpha, OoqpVector & x) inline
y <- beta * y + alpha * A * x
References A, and DoubleMatrix::transMult().
void QpExampleData::Cmult (double beta, OoqpVector & y, double alpha, OoqpVector & x) inline
y <- beta * y + alpha * C * x
References C, and DoubleMatrix::mult().
void QpExampleData::CTransmult (double beta, OoqpVector & y, double alpha, OoqpVector & x) inline
y = beta * y + alpha * C * x
References C, and DoubleMatrix::transMult().
virtual double QpExampleData::datanorm () virtual
compute the norm of the problem data
Implements Data.
void QpExampleData::getb (OoqpVector & b_out) inline
returns right-hand side of equality constraints
References b, and OoqpVector::copyFrom().
void QpExampleData::getd (OoqpVector & d_out) inline
returns right-hand side of inequality constraints
References OoqpVector::copyFrom(), and d.
void QpExampleData::getg (OoqpVector & c_out) inline
returns the linear term from the objective
References c, and OoqpVector::copyFrom().
virtual void QpExampleData::print () virtual
print the problem data
Implements Data.
void QpExampleData::putAIntoAt (SymMatrix & M, int row, int col) inline
put equality constraint matrix A into coefficient matrix of linear system to be solved at each interior-point iteration
References A, my, nx, and SymMatrix::symAtPutSubmatrix().
void QpExampleData::putCIntoAt (SymMatrix & M, int row, int col) inline
put inequality constraint matrix C into coefficient matrix of linear system to be solved at each interior-point iteration
References C, mz, nx, and SymMatrix::symAtPutSubmatrix().
void QpExampleData::putQIntoAt (SymMatrix & M, int row, int col) inline
put Hessian Q into coefficient matrix of linear system to be solved at each interior-point iteration
References nx, Q, and SymMatrix::symAtPutSubmatrix().
void QpExampleData::Qmult (double beta, OoqpVector & y, double alpha, OoqpVector & x) inline
y <- beta * y + alpha * Q * x
References DoubleMatrix::mult(), and Q.
Member Data Documentation
GenMatrix* QpExampleData::A protected
matrix of equality consttaints
Referenced by Amult(), ATransmult(), and putAIntoAt().
OoqpVector* QpExampleData::b protected
right-hand side of equality constraints
Referenced by getb().
GenMatrix* QpExampleData::C protected
matrix of inequality constraints
Referenced by Cmult(), CTransmult(), and putCIntoAt().
OoqpVector* QpExampleData::c protected
linear term in the objective
Referenced by getg().
OoqpVector* QpExampleData::d protected
right-hand side of inequality constraints
Referenced by getd().
int QpExampleData::my protected
number of equality constraints
Referenced by putAIntoAt().
int QpExampleData::mz protected
number of inequality constraints
Referenced by putCIntoAt().
int QpExampleData::nx protected
number of x components
Referenced by putAIntoAt(), putCIntoAt(), and putQIntoAt().
SymMatrix* QpExampleData::Q protected
Hessian of objective
Referenced by putQIntoAt(), and Qmult().
The documentation for this class was generated from the following file:
QpExampleData.h