name: Build test

on: [push, pull_request]

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
        compiler: [gcc, clang] 

    steps:
      - name: Set my secrets
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout DSP
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout DSPThirdPartyLibs
        uses: actions/checkout@v2
        with:
          repository: kibaekkim/DSPThirdPartyLibs
          path: DSPThirdPartyLibs
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          lfs: true
      - name: Run cmake and build
        env:
          MYOS: ${{ matrix.os }}
          CC: ${{ matrix.compiler }}
          FC: gfortran-9
        run: |
          cd DSPThirdPartyLibs
          ./github.sh
          if [ ${{ matrix.os }} == ubuntu-18.04 ]; then export LD_LIBRARY_PATH=$PWD/lib:$(dirname `$FC --print-file-name libgfortran.so`):$LD_LIBRARY_PATH; echo $LD_LIBRARY_PATH; fi
          if [ ${{ matrix.os }} == macos-latest ]; then export DYLD_LIBRARY_PATH=$PWD/lib:$(dirname `$FC --print-file-name libgfortran.dylib`):$DYLD_LIBRARY_PATH; echo $DYLD_LIBRARY_PATH; fi
          cd ..
          mkdir build
          cd build
          if [ ${{ matrix.compiler }} == gcc ]; then export CXX=g++; fi
          if [ ${{ matrix.compiler }} == clang ]; then export CXX=clang++; fi
          cmake .. -DUNIT_TESTING=ON -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=DEBUG
          make -j
          make install
      - name: Unit test
        run: ./src/test/UnitTests
      - name: Test
        run: ctest
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
